DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS StatusOrders;
DROP TABLE IF EXISTS ProductsXOrders;

CREATE TABLE Products(
ProductsID INTEGER PRIMARY KEY AUTOINCREMENT,
Name NVARCHAR(200),
Description NVARCHAR(2000),
Stock INTEGER,
SKU NVARCHAR(200)
);

CREATE TABLE Orders(
OrdersID INTEGER PRIMARY KEY AUTOINCREMENT,
CreatedDate DATETIME,
StatusOrdersID INTEGER
);

CREATE TABLE StatusOrders(
StatusOrdersID INTEGER PRIMARY KEY AUTOINCREMENT,
Name NVARCHAR(200)
);

CREATE TABLE ProductsXOrders(
ProductsXOrdersID INTEGER PRIMARY KEY AUTOINCREMENT,
ProductsID INTEGER,
OrdersID INTEGER,
Amount INTEGER
);

